version: "3.8"

services:
  mongo:
    image: mongo:6
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  netlifybackend:
    build: ./backend
    container_name: netfree-backend
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - MONGO_URI=mongodb://mongo:27017/mern_db
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - mongo

  freemirror:
    build: ./frontend
    container_name: netfree-frontend
    restart: always
    ports:
      - "5173:5173"
    stdin_open: true
    tty: true
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://backend:3000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - netlifybackend

volumes:
  mongo-data:
